kind = "web"
previewPath = "/"
title = "SwebTools"
version = "1.0.0"
id = "artifacts/swebtools"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18915

[services.development]
run = "pnpm --filter @workspace/swebtools run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/swebtools", "run", "build" ]
publicDir = "artifacts/swebtools/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18915"
BASE_PATH = "/"
